    if (StrEqual(weapon, "fa_superx3"))
    {
        weapon = "a Winchester Super X3";
    }
    else if (StrEqual(weapon, "me_sledge"))
    {
        weapon = "a Sledgehammer";
    }
    else if (StrEqual(weapon, "me_fubar"))
    {
        weapon = "a F.U.B.A.R";
    }
    else if (StrEqual(weapon, "fa_glock17"))
    {
        weapon = "a Glock 17";
    }
    else if (StrEqual(weapon, "fa_870"))
    {
        weapon = "a Remington 870";
    }
    else if (StrEqual(weapon, "me_axe_fire"))
    {
        weapon = "a Fireaxe";
    }
    else if (StrEqual(weapon, "me_machete"))
    {
        weapon = "Jason's Machete";
    }
    else if (StrEqual(weapon, "me_bat_metal"))
    {
        weapon = "a Metal Bat";
    }
    else if (StrEqual(weapon, "item_maglite"))
    {
        weapon = "a Fleshlight";
    }
    else if (StrEqual(weapon, "npc_nmrih_shamblerzombie"))
    {
        weapon = "a Dumb Dumb";
    }
    else if (StrEqual(weapon, "npc_nmrih_runnerzombie"))
    {
        weapon = "a Sprinter";
    }
    else if (StrEqual(weapon, "fa_sw686"))
    {
        weapon = "a Smith & Wesson 686";
    }
    else if (StrEqual(weapon, "fa_m16a4"))
    {
        weapon = "a M16A4";
    }
    else if (StrEqual(weapon, "player"))
    {
        weapon = "Suicide";
    }
    else if (StrEqual(weapon, "me_etool"))
    {
        weapon = "a Military Shovel";
    }
    else if (StrEqual(weapon, "fa_500a"))
    {
        weapon = "a Mossberg 500a";
    }
    else if (StrEqual(weapon, "me_kitknife"))
    {
        weapon = "a Kitchen knife";
    }
    else if (StrEqual(weapon, "me_fists"))
    {
        weapon = "their Bare Hands";
    }
    else if (StrEqual(weapon, "me_wrench"))
    {
        weapon = "a Pipe Wrench";
    }
    else if (StrEqual(weapon, "me_cleaver"))
    {
        weapon = "a Butcher's Knife";
    }
    else if (StrEqual(weapon, "fa_sv10"))
    {
        weapon = "a Beretta Perennia SV10";
    }
    else if (StrEqual(weapon, "me_pipe_lead"))
    {
        weapon = "a Lead Pipe";
    }
    else if (StrEqual(weapon, "me_hatchet"))
    {
        weapon = "a Hatchet";
    }
    else if (StrEqual(weapon, "me_shovel"))
    {
        weapon = "a Garden Shovel";
    }
    else if (StrEqual(weapon, "fa_m92fs"))
    {
        weapon = "a Beretta M92FS";
    }
    else if (StrEqual(weapon, "fa_mkiii"))
    {
        weapon = "a Ruger MKIII";
    }
    else if (StrEqual(weapon, "fa_1911"))
    {
        weapon = "a Colt 1911";
    }
    else if (StrEqual(weapon, "fa_1022"))
    {
        weapon = "a Ruger 10/22";
    }
    else if (StrEqual(weapon, "fa_sks"))
    {
        weapon = "a Simonov SKS (Boyonet)";
    }
    else if (StrEqual(weapon, "me_pickaxe"))
    {
        weapon = "a Pickaxe";
    }
    else if (StrEqual(weapon, "fa_1022_25mag"))
    {
        weapon = "a Ruger 10/22 w/ Extended Magezine";
    }
    else if (StrEqual(weapon, "me_crowbar"))
    {
        weapon = "a Crowbar";
    }
    else if (StrEqual(weapon, "fa_winchester1892"))
    {
        weapon = "a Winchester 1892 Lever Action";
    }
    else if (StrEqual(weapon, "fa_sako85"))
    {
        weapon = "a Sako 85 w/ Scope";
    }
    else if (StrEqual(weapon, "npc_nmrih_kidzombie"))
    {
        weapon = "their Children of the Corn";
    }
    else if (StrEqual(weapon, "fa_mac10"))
    {
        weapon = "a MAC-10";
    }
    else if (StrEqual(weapon, "fa_fnfal"))
    {
        weapon = "a FN FAL";
    }
    else if (StrEqual(weapon, "tool_barricade"))
    {
        weapon = "a Barricade Hammer";
    }
    else if (StrEqual(weapon, "fa_cz858"))
    {
        weapon = "a CZ858";
    }
    else if (StrEqual(weapon, "me_chainsaw"))
    {
        weapon = "Leatherface's Chainsaw";
    }
    else if(StrEqual(weapon, "fa_m16a4_carryhandle"))
    {
        weapon = "a M16A4 w/ Carry Handle ";
    }
    else if (StrEqual(weapon, "projectile_arrow"))
    {
        weapon = "a Compound Bow";
    }
    else if (StrEqual(weapon, "me_abrasivesaw"))
    {
        weapon = "an Abrasive Saw";
    }